import { useState, useEffect } from 'react';
import { getHistory, getWeakness, getBankStats, expandBank } from '../api';
import type { HistoryItem, CategoryStat, BankStats } from '../api';
import CategoryPickerModal from './CategoryPickerModal';

interface HomeProps {
  onStartQuiz: () => void;
  onStartWeakQuiz: (categories?: string[]) => void;
  onBrowseBank: () => void;
  onSettings: () => void;
}

export default function Home({ onStartQuiz, onStartWeakQuiz, onBrowseBank, onSettings }: HomeProps) {
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [weakness, setWeakness] = useState<CategoryStat[]>([]);
  const [overallAccuracy, setOverallAccuracy] = useState(0);
  const [bank, setBank] = useState<BankStats | null>(null);
  const [expanding, setExpanding] = useState(false);
  const [showCategoryPicker, setShowCategoryPicker] = useState(false);

  useEffect(() => {
    Promise.all([
      getHistory().catch(() => ({ attempts: [] })),
      getWeakness().catch(() => ({ categories: [], total_seen: 0, overall_accuracy: 0 })),
      getBankStats().catch(() => ({ total: 0, categories: {} })),
    ]).then(([h, w, b]) => {
      setHistory(h.attempts);
      setWeakness(w.categories);
      setOverallAccuracy(w.overall_accuracy);
      setBank(b);
    });
  }, []);

  async function handleExpand() {
    setExpanding(true);
    try {
      const result = await expandBank(25);
      setBank(result.bank);
      alert(`Added ${result.added} new questions! Bank now has ${result.bank.total} questions.`);
    } catch (e: unknown) {
      const msg = e instanceof Error ? e.message : String(e);
      alert('Failed to expand bank: ' + msg);
    }
    setExpanding(false);
  }

  return (
    <div className="home-container">
      <div className="home-topbar">
        <div />
        <button onClick={onSettings} className="settings-gear" title="Settings">⚙</button>
      </div>
      <div className="hero">
        <h1>ISTQB CTFL v4.0</h1>
        <p className="subtitle">AI-Powered Practice Exam</p>
        <p className="hero-desc">
          Each quiz is uniquely generated by GPT-4o with tables, diagrams, and scenarios.
          40 questions • 65% pass mark
        </p>
      </div>

      <div className="action-buttons">
        <button onClick={onStartQuiz} className="action-btn primary-action">
          🚀 Start New Quiz
        </button>
        <button
          onClick={() => setShowCategoryPicker(true)}
          className="action-btn weak-action"
          disabled={weakness.length === 0}
        >
          🎯 Practice Weak Areas
        </button>
      </div>

      {showCategoryPicker && (
        <CategoryPickerModal
          categories={weakness}
          onConfirm={(cats) => {
            setShowCategoryPicker(false);
            onStartWeakQuiz(cats);
          }}
          onClose={() => setShowCategoryPicker(false)}
        />
      )}

      {bank && (
        <div className="bank-section">
          <div className="bank-info">
            <span>📚 Question Bank: <strong>{bank.total}</strong> questions</span>
            <div className="bank-actions">
              <button onClick={onBrowseBank} className="expand-btn">📖 Browse All</button>
              <button
                onClick={handleExpand}
                disabled={expanding}
                className="expand-btn"
              >
                {expanding ? '⏳ Generating...' : '➕ Add 25 via AI'}
              </button>
            </div>
          </div>
        </div>
      )}

      {weakness.length > 0 && (
        <div className="weakness-section">
          <h2>Your Weakness Profile</h2>
          <div className="overall-accuracy">
            Overall: <strong>{overallAccuracy}%</strong> accuracy
          </div>
          <div className="weakness-bars">
            {weakness.map(cat => (
              <div key={cat.category} className="weakness-bar-row">
                <span className="weakness-label">{cat.category}</span>
                <div className="weakness-bar-track">
                  <div
                    className={`weakness-bar-fill ${cat.accuracy >= 65 ? 'good' : 'weak'}`}
                    style={{ width: `${cat.accuracy}%` }}
                  />
                </div>
                <span className="weakness-pct">{cat.accuracy}%</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {history.length > 0 && (
        <div className="history-section">
          <h2>Recent Attempts</h2>
          <table className="history-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Score</th>
                <th>Result</th>
              </tr>
            </thead>
            <tbody>
              {history.slice(0, 10).map(h => (
                <tr key={h.session_id}>
                  <td>{new Date(h.date).toLocaleDateString()}</td>
                  <td>{h.quiz_type === 'weak_area' ? '🎯 Weak Areas' : '📝 Full Quiz'}</td>
                  <td>{h.score ?? '-'}%</td>
                  <td className={h.passed ? 'pass' : 'fail'}>
                    {h.passed ? 'PASS' : 'FAIL'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
